language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lalo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lalo/docker-react yarn test --coverage

#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-west-2"
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: ""# take it from the s3 config.
#  bucket_path: "" # take it from the s3 config.
#  on:
#     branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY
