language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t lalo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lalo/docker-react yarn test --coverage
